export const subNavLinks = [
  { name: "HTML Tutorial", path: "/html-tutorial" },
  { name: "HTML Introduction", path: "/html-introduction" },
  { name: "HTML Editors", path: "/html-editors" },
  { name: "HTML Basics", path: "/html-basics" },
  { name: "HTML Comments", path: "/html-comments" },
  { name: "HTML Elements", path: "/html-elements" },
  { name: "HTML Exercises", path: "/html-exercises" },
  { name: "HTML Tags", path: "/html-tags" },
  { name: "HTML Attributes", path: "/html-attributes" },
  { name: "HTML Headings", path: "/html-headings" },
  { name: "HTML Paragraphs", path: "/html-paragraphs" },
  { name: "HTML Text Formatting", path: "/html-text-formatting" },
  { name: "HTML Quotations", path: "/html-quotations" },
  { name: "HTML Colors", path: "/html-colors" },
  { name: "HTML Links Hyperlinks", path: "/html-links" },
  { name: "HTML Images", path: "/html-images" },
  { name: "HTML Favicon", path: "/html-favicon" },
  { name: "HTML Tables", path: "/html-tables" },
  { name: "HTML Lists", path: "/html-lists" },
  { name: "HTML Ordered Lists", path: "/html-ordered-lists" },
  { name: "HTML Unordered Lists", path: "/html-unordered-lists" },
  { name: "HTML Description Lists", path: "/html-description-lists" },
  { name: "HTML Block and Inline Elements", path: "/html-block-inline" },
  { name: "HTML Iframes", path: "/html-iframes" },
  { name: "HTML File Paths", path: "/html-file-paths" },
  { name: "HTML Layout", path: "/html-layout" },
  { name: "HTML Computer Code Elements", path: "/html-computer-code" },
  { name: "HTML5 Semantics", path: "/html5-semantics" },
  { name: "HTML Entities", path: "/html-entities" },
  { name: "HTML Symbols", path: "/html-symbols" },
  { name: "HTML Emojis", path: "/html-emojis" },
  { name: "HTML Charsets", path: "/html-charsets" },
  { name: "HTML URL Encoding", path: "/html-url-encoding" },
  { name: "HTML Forms", path: "/html-forms" },
  { name: "HTML Responsive Web Design", path: "/html-responsive-design" },
  { name: "HTML Video", path: "/html-video" },
  { name: "Global Attributes", path: "/html-global-attributes" },
  { name: "Event Attributes", path: "/html-event-attributes" },
  { name: "HTML Interview Questions", path: "/html-interview-questions" },
  { name: "HTML DOM", path: "/html-dom" },
  { name: "DOM Audio/Video", path: "/html-dom-audio-video" },
  { name: "HTML 5", path: "/html5" },
  { name: "HTML Examples", path: "/html-examples" },
  { name: "HTML Graphics", path: "/html-graphics" },
  { name: "HTML Tags – A to Z List", path: "/html-tags-a-to-z-list" },
  { name: "HTML Attributes Complete Reference", path: "/html-attributes-complete-reference" },
  { name: "HTML5 Complete Reference", path: "/html5-complete-reference" },
  { name: "HTML5 MathML Complete Reference", path: "/html5-mathml-complete-reference" },
  { name: "HTML DOM Complete Reference", path: "/html-dom-complete-reference" },
  { name: "HTML DOM Audio/Video Complete Reference", path: "/html-dom-audio-video-complete-reference" },
  { name: "SVG Element Complete Reference", path: "/svg-element-complete-reference" },
  { name: "SVG Attribute Complete Reference", path: "/svg-attribute-complete-reference" },
  { name: "SVG Property Complete Reference", path: "/svg-property-complete-reference" },
  { name: "HTML Canvas Complete Reference", path: "/html-canvas-complete-reference" },
  { name: "Color Picker", path: "/html-color-picker" },
  { name: "A to Z Guide", path: "/html-a-to-z-guide" },
  { name: "HTML Formatter", path: "/html-formatter" },
];